## Descripción general de Github Actions
## https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#overview

# +--------------------+
# LÓGICA PRINCIPAL
# +--------------------+

name: Security - Docker - Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ updates ]

jobs:
  scan:
    name: Escanear Docker Imágenes
    runs-on: ubuntu-latest

    steps:
      - name: Permitir acceso repositorio
        uses: actions/checkout@v2

      - name: Forzar Fallo de Seguridad
        run: exit 0
